"""
Post-Incident Report Generator

Generates comprehensive post-incident reports (PIRs) from incident data.
"""

import os
from typing import Dict, Any, List, Optional
from datetime import datetime, timedelta
from pathlib import Path
from dataclasses import dataclass, field
import yaml

try:
    import anthropic
    ANTHROPIC_AVAILABLE = True
except ImportError:
    ANTHROPIC_AVAILABLE = False

try:
    from openai import OpenAI
    OPENAI_AVAILABLE = True
except ImportError:
    OPENAI_AVAILABLE = False


@dataclass
class PostIncidentReport:
    """Represents a generated post-incident report."""
    incident_id: str
    title: str
    service: str
    generated_at: datetime
    duration_minutes: int
    severity: str
    
    # Sections
    executive_summary: str = ""
    timeline: List[Dict[str, str]] = field(default_factory=list)
    impact: Dict[str, Any] = field(default_factory=dict)
    root_cause: str = ""
    contributing_factors: List[str] = field(default_factory=list)
    resolution: str = ""
    lessons_learned: List[str] = field(default_factory=list)
    action_items: List[Dict[str, str]] = field(default_factory=list)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert report to dictionary."""
        return {
            'incident_id': self.incident_id,
            'title': self.title,
            'service': self.service,
            'generated_at': self.generated_at.isoformat(),
            'duration_minutes': self.duration_minutes,
            'severity': self.severity,
            'executive_summary': self.executive_summary,
            'timeline': self.timeline,
            'impact': self.impact,
            'root_cause': self.root_cause,
            'contributing_factors': self.contributing_factors,
            'resolution': self.resolution,
            'lessons_learned': self.lessons_learned,
            'action_items': self.action_items
        }
    
    def to_markdown(self) -> str:
        """Convert report to Markdown format."""
        lines = [
            f"# Post-Incident Report: {self.title}",
            "",
            f"**Incident ID:** {self.incident_id}",
            f"**Service:** {self.service}",
            f"**Date:** {self.generated_at.strftime('%Y-%m-%d')}",
            f"**Duration:** {self.duration_minutes} minutes",
            f"**Severity:** {self.severity.upper()}",
            "",
            "## Executive Summary",
            "",
            self.executive_summary,
            "",
            "## Timeline",
            ""
        ]
        
        for event in self.timeline:
            time = event.get('time', '')
            description = event.get('description', '')
            lines.append(f"- **{time}**: {description}")
        
        lines.extend([
            "",
            "## Impact",
            ""
        ])
        
        if 'error_rate' in self.impact:
            lines.append(f"- Error Rate: {self.impact['error_rate']}")
        if 'affected_users' in self.impact:
            lines.append(f"- Affected Users: {self.impact['affected_users']}")
        if 'affected_requests' in self.impact:
            lines.append(f"- Affected Requests: {self.impact['affected_requests']}")
        
        lines.extend([
            "",
            "## Root Cause",
            "",
            self.root_cause,
            "",
            "## Contributing Factors",
            ""
        ])
        
        for factor in self.contributing_factors:
            lines.append(f"- {factor}")
        
        lines.extend([
            "",
            "## Resolution",
            "",
            self.resolution,
            "",
            "## Lessons Learned",
            ""
        ])
        
        for lesson in self.lessons_learned:
            lines.append(f"- {lesson}")
        
        lines.extend([
            "",
            "## Action Items",
            ""
        ])
        
        for item in self.action_items:
            priority = item.get('priority', 'MEDIUM')
            owner = item.get('owner', 'TBD')
            action = item.get('action', '')
            lines.append(f"- [{priority}] {action} (Owner: {owner})")
        
        lines.extend([
            "",
            "---",
            "",
            f"*Report generated by Living Runbooks on {self.generated_at.strftime('%Y-%m-%d %H:%M')}*"
        ])
        
        return "\n".join(lines)


class IncidentReportGenerator:
    """
    Generates comprehensive post-incident reports.
    
    Uses LLM to analyze incident data and generate structured reports.
    """
    
    def __init__(self, provider: str = "anthropic", api_key: Optional[str] = None):
        """
        Initialize report generator.
        
        Args:
            provider: LLM provider ('anthropic' or 'openai')
            api_key: API key
        """
        self.llm = None
        
        if provider == "anthropic" and ANTHROPIC_AVAILABLE:
            self.llm = anthropic.Anthropic(api_key=api_key or os.environ.get('ANTHROPIC_API_KEY'))
        elif provider == "openai" and OPENAI_AVAILABLE:
            self.llm = OpenAI(api_key=api_key or os.environ.get('OPENAI_API_KEY'))
    
    def generate_report(
        self,
        incident_data: Dict[str, Any],
        annotations: Optional[List[Dict[str, Any]]] = None,
        diagnostics: Optional[List[Dict[str, Any]]] = None,
        runbook_steps: Optional[List[Dict[str, Any]]] = None
    ) -> PostIncidentReport:
        """
        Generate a post-incident report.
        
        Args:
            incident_data: Core incident information
            annotations: Optional list of annotations from runbook
            diagnostics: Optional diagnostic data
            runbook_steps: Optional runbook steps that were executed
        
        Returns:
            Generated PostIncidentReport
        """
        # Build the prompt
        prompt = self._build_report_prompt(
            incident_data,
            annotations,
            diagnostics,
            runbook_steps
        )
        
        # Generate content using LLM
        if self.llm:
            report_content = self._generate_with_llm(prompt)
        else:
            # Fallback to template-based generation
            report_content = self._generate_template_report(incident_data, annotations)
        
        # Parse the generated content
        report = self._parse_report_content(incident_data, report_content)
        
        return report
    
    def _build_report_prompt(
        self,
        incident_data: Dict[str, Any],
        annotations: Optional[List[Dict[str, Any]]],
        diagnostics: Optional[List[Dict[str, Any]]],
        runbook_steps: Optional[List[Dict[str, Any]]]
    ) -> str:
        """Build the prompt for report generation."""
        
        prompt = f"""You are an expert SRE writing a post-incident report. Generate a comprehensive, professional report based on the following incident data.

**Incident Information:**
- Incident ID: {incident_data.get('incident_id', 'UNKNOWN')}
- Title: {incident_data.get('title', 'Untitled Incident')}
- Service: {incident_data.get('service', 'Unknown')}
- Severity: {incident_data.get('severity', 'Unknown')}
- Duration: {incident_data.get('duration_minutes', 'Unknown')} minutes
- Root Cause: {incident_data.get('cause', 'Unknown')}
- Fix Applied: {incident_data.get('fix', 'Unknown')}

"""
        
        if annotations:
            prompt += "**Annotations from Runbook:**\n"
            for ann in annotations:
                prompt += f"- {ann.get('incident_id')}: {ann.get('cause')} → {ann.get('fix')}\n"
            prompt += "\n"
        
        if diagnostics:
            prompt += f"**Diagnostic Data:** {len(diagnostics)} diagnostics captured\n"
        
        if runbook_steps:
            prompt += "**Runbook Steps Executed:**\n"
            for i, step in enumerate(runbook_steps[:5], 1):
                prompt += f"{i}. {step.get('check', 'Unknown step')}\n"
            prompt += "\n"
        
        prompt += """**Generate a report with the following sections:**

1. **Executive Summary** (2-3 sentences summarizing the incident)
2. **Timeline** (list of events with timestamps)
3. **Impact** (error rates, affected users, affected requests)
4. **Root Cause** (detailed technical explanation)
5. **Contributing Factors** (list of factors that led to the incident)
6. **Resolution** (steps taken to resolve)
7. **Lessons Learned** (3-5 key takeaways)
8. **Action Items** (specific tasks with priority and owner)

Format the response as valid JSON with these exact keys:
- executive_summary
- timeline (array of objects with 'time' and 'description')
- impact (object with relevant metrics)
- root_cause
- contributing_factors (array of strings)
- resolution
- lessons_learned (array of strings)
- action_items (array of objects with 'action', 'priority', 'owner')

Return ONLY the JSON, no additional text."""
        
        return prompt
    
    def _generate_with_llm(self, prompt: str) -> str:
        """Generate report content using LLM."""
        try:
            if isinstance(self.llm, anthropic.Anthropic):
                response = self.llm.messages.create(
                    model="claude-3-5-sonnet-20241022",
                    max_tokens=2000,
                    messages=[{"role": "user", "content": prompt}]
                )
                return response.content[0].text
            
            elif isinstance(self.llm, OpenAI):
                response = self.llm.chat.completions.create(
                    model="gpt-4o",
                    messages=[{"role": "user", "content": prompt}],
                    max_tokens=2000
                )
                return response.choices[0].message.content
        
        except Exception as e:
            print(f"LLM generation failed: {e}")
            return "{}"
        
        return "{}"
    
    def _parse_report_content(
        self,
        incident_data: Dict[str, Any],
        content: str
    ) -> PostIncidentReport:
        """Parse generated content into PostIncidentReport."""
        import json
        
        # Try to extract JSON from content
        try:
            # Find JSON in response (might be wrapped in markdown)
            start = content.find('{')
            end = content.rfind('}') + 1
            
            if start >= 0 and end > start:
                json_str = content[start:end]
                data = json.loads(json_str)
            else:
                data = {}
        except (json.JSONDecodeError, ValueError):
            data = {}
        
        # Calculate duration
        created_at = incident_data.get('created_at')
        resolved_at = incident_data.get('resolved_at')
        
        if created_at and resolved_at:
            try:
                if isinstance(created_at, str):
                    created_at = datetime.fromisoformat(created_at.replace('Z', '+00:00'))
                if isinstance(resolved_at, str):
                    resolved_at = datetime.fromisoformat(resolved_at.replace('Z', '+00:00'))
                duration = int((resolved_at - created_at).total_seconds() / 60)
            except:
                duration = incident_data.get('duration_minutes', 0)
        else:
            duration = incident_data.get('duration_minutes', 0)
        
        return PostIncidentReport(
            incident_id=incident_data.get('incident_id', 'UNKNOWN'),
            title=incident_data.get('title', 'Untitled Incident'),
            service=incident_data.get('service', 'Unknown'),
            generated_at=datetime.now(),
            duration_minutes=duration,
            severity=incident_data.get('severity', 'Unknown'),
            executive_summary=data.get('executive_summary', ''),
            timeline=data.get('timeline', []),
            impact=data.get('impact', {}),
            root_cause=data.get('root_cause', incident_data.get('cause', '')),
            contributing_factors=data.get('contributing_factors', []),
            resolution=data.get('resolution', incident_data.get('fix', '')),
            lessons_learned=data.get('lessons_learned', []),
            action_items=data.get('action_items', [])
        )
    
    def _generate_template_report(
        self,
        incident_data: Dict[str, Any],
        annotations: Optional[List[Dict[str, Any]]]
    ) -> str:
        """Generate a basic report without LLM."""
        
        # Build timeline from annotations
        timeline = []
        if annotations:
            for ann in annotations:
                timeline.append({
                    'time': ann.get('timestamp', 'Unknown'),
                    'description': f"Incident annotated: {ann.get('cause', 'Unknown cause')}"
                })
        
        # Build basic report
        report = {
            'executive_summary': f"Service {incident_data.get('service', 'Unknown')} experienced an incident ({incident_data.get('incident_id', 'UNKNOWN')}) caused by {incident_data.get('cause', 'unknown causes')}. The issue was resolved by {incident_data.get('fix', 'applying a fix')}.",
            'timeline': timeline,
            'impact': {
                'duration_minutes': incident_data.get('duration_minutes', 0),
                'severity': incident_data.get('severity', 'Unknown')
            },
            'root_cause': incident_data.get('cause', 'Root cause not documented'),
            'contributing_factors': ['See runbook for detailed analysis'],
            'resolution': incident_data.get('fix', 'Fix applied'),
            'lessons_learned': [
                'Review monitoring coverage',
                'Update runbook with lessons from this incident',
                'Consider automation for faster detection'
            ],
            'action_items': [
                {'action': 'Update runbook', 'priority': 'HIGH', 'owner': 'On-call team'},
                {'action': 'Review monitoring', 'priority': 'MEDIUM', 'owner': 'SRE team'}
            ]
        }
        
        import json
        return json.dumps(report)
    
    def save_report(
        self,
        report: PostIncidentReport,
        output_path: str,
        format: str = 'markdown'
    ) -> str:
        """
        Save report to file.
        
        Args:
            report: Report to save
            output_path: Path to save file
            format: Output format ('markdown' or 'json')
        
        Returns:
            Path to saved file
        """
        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)
        
        if format == 'json':
            with open(output_file, 'w', encoding='utf-8') as f:
                json.dump(report.to_dict(), f, indent=2)
        else:
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(report.to_markdown())
        
        return str(output_file)


def main():
    """Example usage of report generator."""
    import argparse
    import json
    
    parser = argparse.ArgumentParser(
        description="Generate post-incident reports"
    )
    parser.add_argument(
        "--incident",
        required=True,
        help="Path to incident JSON file"
    )
    parser.add_argument(
        "--runbook",
        help="Path to runbook YAML file"
    )
    parser.add_argument(
        "--output",
        help="Output file path"
    )
    parser.add_argument(
        "--format",
        choices=['markdown', 'json'],
        default='markdown',
        help="Output format"
    )
    parser.add_argument(
        "--provider",
        choices=['anthropic', 'openai', 'template'],
        default='template',
        help="Generation provider"
    )
    
    args = parser.parse_args()
    
    # Load incident data
    with open(args.incident, 'r') as f:
        incident_data = json.load(f)
    
    # Load runbook if provided
    annotations = None
    runbook_steps = None
    
    if args.runbook:
        with open(args.runbook, 'r') as f:
            runbook = yaml.safe_load(f)
            annotations = runbook.get('annotations', [])
            runbook_steps = runbook.get('steps', [])
    
    # Generate report
    generator = IncidentReportGenerator(provider=args.provider)
    report = generator.generate_report(
        incident_data,
        annotations=annotations,
        runbook_steps=runbook_steps
    )
    
    # Output report
    if args.output:
        output_path = generator.save_report(report, args.output, format=args.format)
        print(f"Report saved to {output_path}")
    else:
        if args.format == 'json':
            print(json.dumps(report.to_dict(), indent=2))
        else:
            print(report.to_markdown())


if __name__ == "__main__":
    main()
